name: hatud_tricycle_app
description: HATUD - Tricycle Ride Booking App with multi-language support (English, Tagalog, Waray-Waray)

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^8.1.4
  # Singleton access
  get_it: ^7.7.0
  # Value equality
  equatable: ^2.0.5
  # Remote API
  dio: ^5.6.0
  # Connectivity (replaces deprecated data_connection_checker)
  internet_connection_checker: ^1.0.0+1
  # Local cache
  shared_preferences: ^2.3.2
  # Use Either
  dartz: ^0.10.1
  # Device info (replaces deprecated device_info)
  device_info_plus: ^10.1.2
  # Rating bar
  flutter_rating_bar: ^4.0.1
  # Google map
  google_maps_flutter: ^2.7.0
  webview_flutter: ^4.4.2
  # OpenStreetMap
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  # Draw dotted border
  dotted_border: ^2.1.0
  # Country picker
  # country_pickers: 1.1.0
  # Shimmer
  shimmer: ^3.0.0
  # Hive NoSQL database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Permission handler
  permission_handler: ^11.3.1
  # Geolocator
  geolocator: ^12.0.0
  # HTTP client for API calls
  http: ^1.2.0
  # Share content (replaces deprecated share)
  share_plus: ^10.0.2
  # Image picker for camera and gallery
  image_picker: ^1.0.7
  # URL launcher for opening links
  url_launcher: ^6.2.5
  # Supabase client
  supabase_flutter: ^2.6.0
  # UUID helper (optional)
  uuid: ^4.4.2
  # Camera for face recognition
  camera: ^0.11.0+2
  # Google ML Kit Face Detection
  google_mlkit_face_detection: ^0.13.1
  # Google ML Kit Text Recognition
  google_mlkit_text_recognition: ^0.15.0
  # Image processing
  image: ^4.3.0
  # Gallery access
  gal: ^2.0.1
  # Audio player for SOS alerts
  audioplayers: ^6.1.0
  # Scrollable bottom sheet (removed due to null-safety constraints)
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # cleanup legacy loose deps added by automated fix
  bloc: any
  vector_math: any
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/locale/
      - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: GT-Eesti
       fonts:
          - asset: fonts/GT-Eesti-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: ViitIcons
       fonts:
          - asset: fonts/ViitIcons.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
